### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Fornoth** [Fornoth/spotify-connect-web#15]
- [x] Add volume scaling option (#11, #22)
- [x] Add option to close/open ALSA device/restart audio thread (#11, #12, #17, fixed in #18)
- [ ] Give more information on library not found errors
- [x] Upgrade to pyalsaaudio 0.8+
- [ ] Implement audio flushing
- [ ] Add info about mixers/softvol to readme (#11)
- [ ] Use paths relative to the script for cffi
- [ ] Add config file (for storing stuff like the display name)
- [ ] Fix playback stopping issue (#41)
- [ ] Add larger player (#43)
- [x] Fix bug in volume api that doesn't allow the volume to be 0
- [ ] Add plugin support (#46)
- [ ] Add support to output to a FIFO (#48)
- [ ] Fix flask-cors import (https://github.com/Fornoth/spotify-connect-web/commit/b95bda261f68b55413e7e35c32f6193633c11411 )
- [ ] Migrate to Tornado for a web server instead of gevent
- [ ] Delete credentials if they're invalid (#54)
- [ ] Write some tests to verify basic functionality works on every release
- [ ] Add a way to get playback info from connect.py (#61)
- [ ] Add error message about invalid login (#78)
- [ ] Handle when a device doesn't have a mixer
- [ ] Figure out why volume doesn't work in this plugin (https://github.com/Fornoth/spotify-connect-web/issues/11#issuecomment-255459513)
- [ ] Add option to mount ALSA audio conf from host in chroot
- [ ] Fix mixer[0] issue (#120)
- [ ] Update chroot to check for existing mounts (#119)

**Comment by dialupdev** [comment]
@Fornoth What's blocking the upgrade to pyalsaaudio 0.8+? I can upgrade on my Pi3 with no problems. Is there particular hardware that it doesn't currently work on?

**Comment by Fornoth** [comment]
@celeryclub pyalsaaudio 0.8+ itself works fine, the note is more to upgrade to the newer device/mixer selection features in it

**Comment by dialupdev** [comment]
@Fornoth Understood. Thanks.

**Comment by ghost** [comment]
> Handle when a device doesn't have a mixer

I guess this is the reason why my HifiBerry DAC+ light won't play along with Spotify Connect Web. Is this something that's very hard to fix? If not, can you point me in the right direction, so I can see if I can figure it out?

**Comment by awiouy** [comment]
@makruiten 
I use the following for my HifiBerry DAC+ on libreELEC:
playback device: default:CARD=sndrpihifiberry
mixer: Digital

**Comment by ghost** [comment]
@awiouy 
Is that the light version? The other two have mixers, but the light version lacks one.

**Comment by ClemaX** [comment]
@makruiten For me the DAC+ Light works, I have got no volume control tho. I'm using the latest runeaudio for the raspberry pi 3.
The lack of a hardware mixer is the reason why we need to use the software mixer.

**Comment by ghost** [comment]
@ClemaX It was probably due to the way it is packaged in Kodi. I had no problems getting it to work in Volumio. In Kodi you are forced to select a mixer, while there are none. Or at least I was unable to get it up and running.

**Comment by ClemaX** [comment]
@makruiten Have you tried adding a software mixer to the alsa asound.conf config file?

**Comment by Fornoth** [comment]
You can see #11 for software volume mixing
